#!/usr/bin/env python3
"""Embed the runtime's own Lua source into the plugin as C string literals.

The scheduler and resource manager are Lua, not C++: without an STL, thread
lists and handler tables in C++ would be hand-rolled data structures, and the
spec's own pseudocode is already Lua. Keeping the source as real .lua files in
the repo means it stays syntax-checkable (luac5.4 -p) and host-testable with a
stock lua5.4, while the .prx stays self-contained.

The .lua files under src/script/lua/ are the source of record; the generated
header is committed so a contributor without Python still builds, but it is
regenerated from those files, never hand-edited.

The escaper appends a trailing "\n" to every line, including the last, so a
source file with no trailing newline gains one in the embedded copy. That is
inert to Lua (a chunk does not care whether it ends in a blank line) and is
the only way the embedded text differs from the file on disk.

    python tools/gen_embedded_lua.py              ->  src/script/embedded_lua.h
    python tools/gen_embedded_lua.py --out PATH   ->  PATH

--out exists for tests/run.sh's freshness gate, which regenerates to a temp
file and diffs it against the committed header. That gate must never be able
to "fix" the mismatch it is looking for by overwriting the committed file, so
it needs somewhere else to write.
"""

import io, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC_DIR = os.path.join(HERE, "..", "src", "script", "lua")
OUT = os.path.join(HERE, "..", "src", "script", "embedded_lua.h")

# Load order matters: boot.lua runs last and expects the others to have
# populated __rt. Listed explicitly rather than globbed, so adding a chunk is a
# deliberate edit and the order is never left to directory listing.
ORDER = ["scheduler.lua", "manifest.lua", "api.lua", "resource.lua", "boot.lua"]


def c_string(text):
    """Escape one Lua source file into a C string literal, one line per line so
    a compiler error points at something a human can find."""
    out = []
    for line in text.split("\n"):
        esc = line.replace("\\", "\\\\").replace('"', '\\"')
        out.append('    "%s\\n"' % esc)
    return "\n".join(out)


def parse_args(argv):
    """Just --out. argparse would do, but this file is deliberately a
    stdlib-only script a contributor can read top to bottom, and an unknown
    argument must be a hard error rather than something silently ignored --
    a typo'd --out that wrote over the committed header is precisely what the
    freshness gate exists to catch, so it must not be reachable by accident."""
    out = OUT
    args = list(argv)
    while args:
        a = args.pop(0)
        if a == "--out":
            if not args:
                sys.exit("FATAL: --out needs a path")
            out = args.pop(0)
        else:
            sys.exit("FATAL: unknown argument %r "
                     "(usage: gen_embedded_lua.py [--out PATH])" % a)
    return out


def main(out):
    chunks = []
    for name in ORDER:
        path = os.path.join(SRC_DIR, name)
        if not os.path.isfile(path):
            # ORDER is a short, deliberate list and every entry is load-bearing:
            # a typo or a rename here must not silently produce a header that
            # is valid and incomplete (tests/run.sh's syntax gate globs only
            # the files that DO exist, so it would never catch this). This is
            # a structural failure, not a per-item loss to tally and continue
            # past the way gen_natives_lua.py's skip counter does across
            # thousands of natives.
            sys.exit("FATAL: %s listed in ORDER but not found at %s" %
                      (name, os.path.normpath(path)))
        with io.open(path, encoding="utf-8") as f:
            chunks.append((name, f.read()))

    lines = [
        "#pragma once",
        "// GENERATED by tools/gen_embedded_lua.py - do not edit by hand.",
        "//",
        "// The runtime's own Lua, compiled into the plugin. Edit the files in",
        "// src/script/lua/ and regenerate; they are the source of record.",
        "",
        "namespace script {",
        "",
        "struct embedded_chunk {",
        "    const char* name;",
        "    const char* src;",
        "};",
        "",
        "// Load order is significant - see tools/gen_embedded_lua.py.",
        "static const embedded_chunk EMBEDDED_LUA[] = {",
    ]
    for name, text in chunks:
        lines.append('    { "%s",' % name)
        lines.append(c_string(text))
        lines.append("    },")
    lines.append("    { nullptr, nullptr },")
    lines.append("};")
    lines.append("")
    lines.append("}  // namespace script")
    lines.append("")

    with io.open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    total = sum(len(t) for _, t in chunks)
    print("chunks embedded   : %d" % len(chunks))
    print("total source bytes: %d" % total)
    print("output            : %s" % os.path.normpath(out))


if __name__ == "__main__":
    main(parse_args(sys.argv[1:]))
