# CMake toolchain file for the OpenOrbis PS4 Toolchain.
# Generated by OrbisForge. Requires the OO_PS4_TOOLCHAIN environment variable.
#
# Usage: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=cmake/oo-ps4-toolchain.cmake

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

if(NOT DEFINED ENV{OO_PS4_TOOLCHAIN})
    message(FATAL_ERROR "OO_PS4_TOOLCHAIN environment variable is not set")
endif()
set(OO_PS4_TOOLCHAIN "$ENV{OO_PS4_TOOLCHAIN}" CACHE PATH "OpenOrbis PS4 toolchain root")
set(OO_PS4_TOOLCHAIN_BIN "${OO_PS4_TOOLCHAIN}/bin/linux" CACHE PATH "OpenOrbis PS4 toolchain host tools")

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)

set(CMAKE_C_COMPILER_TARGET   x86_64-pc-freebsd12-elf)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-freebsd12-elf)

# CMake's compiler sanity check tries to link a full executable, which fails
# against this target unless we skip straight to a static-library try-compile.
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(_oo_common_flags "-fPIC -funwind-tables -isysroot ${OO_PS4_TOOLCHAIN} -isystem ${OO_PS4_TOOLCHAIN}/include")
set(CMAKE_C_FLAGS_INIT   "${_oo_common_flags}")
set(CMAKE_CXX_FLAGS_INIT "${_oo_common_flags} -isystem ${OO_PS4_TOOLCHAIN}/include/c++/v1")

# Base linker setup shared by every target. The CRT start object and the
# -l libs are added per-target by add_orbis_target() below, since
# executables and libraries need different CRT objects (crt1.o vs crtlib.o).
set(CMAKE_EXE_LINKER_FLAGS_INIT
    "-fuse-ld=lld -nostdlib -nostartfiles -pie -Wl,--script=${OO_PS4_TOOLCHAIN}/link.x -Wl,--eh-frame-hdr -L${OO_PS4_TOOLCHAIN}/lib"
)

include("${CMAKE_CURRENT_LIST_DIR}/OrbisTargets.cmake")